In [1]:
import numpy as np

# generate a random int matrix of size 4x3

matrix = np.random.randint(0, 10, (4, 3))

print(matrix)

[[4 4 7]
 [8 9 4]
 [2 2 8]
 [1 5 7]]


In [5]:
#NMF
from sklearn.decomposition import NMF

model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(matrix)
H = model.components_
print(W)
print(H)
np.dot(W, H)

[[1.91119755 0.52591007]
 [1.03591987 1.75194427]
 [2.2162929  0.        ]
 [2.01059234 0.28579951]]
[[0.59392576 1.1958961  3.5624934 ]
 [4.19797015 4.44645011 0.17401216]]


array([[3.3428642 , 4.62402656, 6.9001434 ],
       [7.96986922, 9.02878531, 3.99531731],
       [1.31631344, 2.65045604, 7.89552885],
       [2.3939204 , 3.67525281, 7.21245453]])

In [ ]:
# SSMF
normX1 = np.linalg.norm(matrix,axis=0, ord=1)
normW1 = np.linalg.norm(W,axis=0, ord=1)
W_new = W/normW1
H_new = (H.T*normW1).T/normX1
X_new = np.dot(W_new, H_new)


[[0.22285761 0.23120133 0.26539013]
 [0.53132461 0.45143927 0.15366605]
 [0.08775423 0.1325228  0.30367419]
 [0.15959469 0.18376264 0.2774021 ]]


array([[3.3428642 , 4.62402656, 6.9001434 ],
       [7.96986922, 9.02878531, 3.99531731],
       [1.31631344, 2.65045604, 7.89552885],
       [2.3939204 , 3.67525281, 7.21245453]])

In [ ]:
clc;clear;close all;

x=-4:0.01:4;
y=gaussmf(x,[1,0]);
plot(x,y,'b','LineWidth',2);hold on;
axis([-4 4 0 1.001])

%% 置信区间边界
plot([-2,-2],[0,gaussmf(-2,[1,0])],'k','LineWidth',2);hold on
plot([2,2],[0,gaussmf(2,[1,0])],'k','LineWidth',2);hold on
%% 置信区间颜色填充
for i=1:floor(length(x)/4)
    plot([x(i),x(i)],[0,gaussmf(x(i),[1,0])],'Color',[0.35,0,0.6],'LineWidth',2);hold on 
end
for i=1:floor(length(x)/4)
    ind=x(x>2);
    plot([ind(i),ind(i)],[0,gaussmf(ind(i),[1,0])],'Color',[0.35,0,0.6],'LineWidth',2);hold on 
end
%% 图中标注设置
set(gca,'XTicklabel',{' ',' ','\mu-2\sigma',' ','\mu',' ','\mu+2\sigma',' '},'fontsize',15)
set(gca,'YTicklabel',[])
annotation('arrow',[0.27,0.30],[0.24,0.20],'LineWidth',2)
annotation('arrow',[0.76,0.73],[0.24,0.20],'LineWidth',2)
text(-3,0.20,'\alpha/2=0.025','color','r','fontsize',15)
text(2.1,0.20,'\alpha/2=0.025','color','r','fontsize',15)

title('The 95% confidence interval for \mu','fontsize',15)

