In [1]:
import numpy as np

# generate a random int matrix of size 4x3

matrix = np.random.randint(0, 10, (4, 3))

print(matrix)

[[4 4 7]
 [8 9 4]
 [2 2 8]
 [1 5 7]]


In [5]:
#NMF
from sklearn.decomposition import NMF

model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(matrix)
H = model.components_
print(W)
print(H)
np.dot(W, H)

[[1.91119755 0.52591007]
 [1.03591987 1.75194427]
 [2.2162929  0.        ]
 [2.01059234 0.28579951]]
[[0.59392576 1.1958961  3.5624934 ]
 [4.19797015 4.44645011 0.17401216]]


array([[3.3428642 , 4.62402656, 6.9001434 ],
       [7.96986922, 9.02878531, 3.99531731],
       [1.31631344, 2.65045604, 7.89552885],
       [2.3939204 , 3.67525281, 7.21245453]])

In [ ]:
# SSMF
normX1 = np.linalg.norm(matrix,axis=0, ord=1)
normW1 = np.linalg.norm(W,axis=0, ord=1)
W_new = W/normW1
H_new = (H.T*normW1).T/normX1
X_new = np.dot(W_new, H_new)


[[0.22285761 0.23120133 0.26539013]
 [0.53132461 0.45143927 0.15366605]
 [0.08775423 0.1325228  0.30367419]
 [0.15959469 0.18376264 0.2774021 ]]


array([[3.3428642 , 4.62402656, 6.9001434 ],
       [7.96986922, 9.02878531, 3.99531731],
       [1.31631344, 2.65045604, 7.89552885],
       [2.3939204 , 3.67525281, 7.21245453]])